[pytest]
addopts = -s -v
    --html=reports/report.html
    --self-contained-html
    --alluredir=allure-results --clean-alluredir
testpaths = .
python_files = test_*.py *_test.py
markers =
    ui: marks Playwright-based UI tests
log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s | %(levelname)s | %(name)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
